version: '3'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD-changeme}
    ports:
      - '3306:3306'
    volumes:
      - ./data/mariadb-config:/etc/mysql/conf.d
      - ./data/mariadb-data:/var/lib/mysql

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    depends_on:
      - mariadb      
    environment:
      - DB_MYSQL_HOST=mariadb
      - DB_MYSQL_NAME=${NGINX_MYSQL_NAME}
      - DB_MYSQL_USER=${NGINX_MYSQL_USER}
      - DB_MYSQL_PASSWORD=${NGINX_MYSQL_PASSWORD}
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt

  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

networks:

  default:
    name: proxy
