version: '3'

services:

  devstack:
    build: ./src/devstack
    container_name: devstack
    hostname: devstack
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mysql://${DEVSTACK_MYSQL_USER}:${DEVSTACK_MYSQL_PASSWORD}@mariadb:3306/${DEVSTACK_MYSQL_NAME}
      - VIRTUAL_HOST=devstack.${TLD-local}

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD-changeme}
    ports:
      - '3306:3306'
    volumes:
      - ./data/mariadb-config:/etc/mysql/conf.d
      - ./data/mariadb-data:/var/lib/mysql

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/nginx-certs:/etc/nginx/certs:ro
      - ./data/nginx-config:/etc/nginx/conf.d
      - ./data/nginx-html:/usr/share/nginx/html
      - ./data/nginx-vhosts:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  wordpress:
    build: ./src/wordpress
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - APACHE2_TLD=${APACHE2_TLD-local}
      - VIRTUAL_HOST=*.${TLD-local}
    volumes:
      - ./data/wordpress-config:/etc/apache2/conf-extra
      - ./data/wordpress-html:/var/www/html
      - ./data/wordpress-logs:/var/log/apache2
      - ./data/wordpress-tmp:/tmp

networks:

  default:
    name: proxy
